"""
Markdown examination report.

The section order deliberately mirrors the Case 029 report — Scenario,
Collection, Preservation, Analysis, Conclusion, Reflection, Audit Trail — so a
generated report can be dropped straight into an existing case file, and so a
reviewer familiar with the manual document can navigate the automated one
without re-learning the layout.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence

from ffxforensics.audit import AuditTrail
from ffxforensics.case import CaseResult

MAX_TABLE_ROWS = 60


def _esc(value: Any) -> str:
    """Escape a value for safe inclusion in a Markdown table cell."""
    text = "" if value is None else str(value)
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _table(headers: Sequence[str], rows: Sequence[Sequence[Any]]) -> str:
    if not rows:
        return "_No records recovered._\n"
    head = "| " + " | ".join(headers) + " |"
    sep = "|" + "|".join("---" for _ in headers) + "|"
    body = "\n".join("| " + " | ".join(_esc(cell) for cell in row) + " |" for row in rows)
    return f"{head}\n{sep}\n{body}\n"


def _flatten(value: Any) -> str:
    """Render list values (e.g. the mismatched-file list) readably."""
    if isinstance(value, (list, tuple)):
        return ", ".join(str(item) for item in value) if value else "none"
    return str(value)


def _truncated_note(total: int, shown: int) -> str:
    if total <= shown:
        return ""
    return (
        f"\n> Showing the first {shown} of {total} rows. "
        f"The complete set is in the accompanying CSV export.\n"
    )


def render_markdown(
    result: CaseResult,
    trail: Optional[AuditTrail] = None,
    max_rows: int = MAX_TABLE_ROWS,
) -> str:
    """Render the full examination report as Markdown text."""
    meta = result.metadata
    parts: List[str] = []

    # ---------------------------------------------------------------- header
    parts.append(f"# Digital Forensics Examination Report — Case {meta.case_id}\n")
    parts.append(
        "> Generated by **ffxforensics** — reproduce with "
        "`ffxforensics analyze <evidence-dir>`.\n"
    )

    admin_rows = [
        ["Case / file number", meta.case_id],
        ["Examiner", meta.examiner],
        ["Subject of examination", meta.subject],
        ["Organisation", meta.organisation],
        ["Exhibit reference", meta.exhibit_reference],
        ["Device", meta.device],
        ["Operating system", meta.operating_system],
        ["Browser", meta.browser],
        ["Evidence set", meta.evidence_name],
        ["Evidence path", str(result.evidence_dir)],
        ["Report generated (UTC)", result.generated_utc],
        ["Timestamps rendered in", result.timezone],
    ]
    parts.append("## 1. Investigative context\n")
    parts.append(_table(["Field", "Value"], [row for row in admin_rows if row[1]]))

    if meta.notes:
        parts.append(f"\n**Notes:** {meta.notes}\n")

    # ------------------------------------------------------------- artefacts
    parts.append("\n## 2. Evidence handled and integrity\n")
    parts.append(
        "Each artefact below was opened **read-only and immutable** "
        "(`file:...?mode=ro&immutable=1`), so no journal or WAL side-file was "
        "created and the acquisition hash remains valid (ACPO Principles 1 & 2).\n\n"
    )
    artefact_rows = [
        [
            data.get("file", name),
            f"{data.get('size_bytes', 0):,}",
            data.get("sha256", ""),
            data.get("integrity_check", ""),
        ]
        for name, data in result.artefacts.items()
    ]
    parts.append(
        _table(["Artefact", "Size (bytes)", "SHA-256", "PRAGMA integrity_check"], artefact_rows)
    )

    if result.integrity:
        parts.append("\n**Manifest verification**\n\n")
        parts.append(
            _table(
                ["Check", "Result"],
                [[key, _flatten(value)] for key, value in result.integrity.items()],
            )
        )

    if result.statistics:
        parts.append("\n**Record counts**\n\n")
        stat_rows = [
            [artefact, key, value]
            for artefact, stats in result.statistics.items()
            for key, value in stats.items()
        ]
        parts.append(_table(["Artefact", "Metric", "Count"], stat_rows))

    # -------------------------------------------------------------- analysis
    parts.append("\n## 3. Analysis\n")

    parts.append("\n### 3.1 Activity window\n\n")
    window = result.window or {}
    parts.append(
        _table(
            ["Measure", "Value"],
            [
                ["First recorded event", window.get("first", "n/a")],
                ["Last recorded event", window.get("last", "n/a")],
                ["Span (seconds)", window.get("span_seconds", 0)],
                ["Timeline events", window.get("event_count", 0)],
                ["Sessions (30-minute gap)", len(result.sessions)],
            ],
        )
    )

    if result.sessions:
        parts.append("\n**Sessions**\n\n")
        parts.append(
            _table(
                ["#", "Start", "End", "Duration", "Events", "Flagged"],
                [
                    [
                        session.index,
                        session.start.strftime("%Y-%m-%d %H:%M:%S") if session.start else "",
                        session.end.strftime("%Y-%m-%d %H:%M:%S") if session.end else "",
                        session.duration_human,
                        len(session.events),
                        sum(1 for event in session.events if event.indicators),
                    ]
                    for session in result.sessions
                ],
            )
        )

    # searches
    parts.append("\n### 3.2 Search queries recovered from history\n\n")
    searches = result.searches[:max_rows]
    parts.append(
        _table(
            ["Search query", "Engine", "Last visited"],
            [[item.query, item.engine, item.last_visited_str] for item in searches],
        )
    )
    parts.append(_truncated_note(len(result.searches), len(searches)))

    # video
    if result.video_visits:
        parts.append("\n### 3.3 Video platform activity\n\n")
        videos = result.video_visits[:max_rows]
        parts.append(
            _table(
                ["Link", "Title", "Most recent activity"],
                [[item.url, item.title, item.visit_date_str] for item in videos],
            )
        )
        parts.append(_truncated_note(len(result.video_visits), len(videos)))

    # bookmarks
    parts.append("\n### 3.4 Bookmarks\n\n")
    bookmarks = result.bookmark_entries[:max_rows]
    parts.append(
        _table(
            ["Bookmark", "URL", "Folder", "Last modified"],
            [
                [item.title, item.url, item.folder_path, item.last_modified_str]
                for item in bookmarks
            ],
        )
    )
    parts.append(_truncated_note(len(result.bookmark_entries), len(bookmarks)))

    # visit types
    parts.append("\n### 3.5 Navigation categories (`moz_historyvisits.visit_type`)\n\n")
    parts.append(
        "Distinguishes deliberate navigation from passive redirection: a typed "
        "URL (category 2) carries more evidential weight than a redirect "
        "(categories 5 and 6).\n\n"
    )
    parts.append(
        _table(
            ["Visit category", "Meaning", "Web presence count"],
            [[code, data["label"], data["count"]] for code, data in result.visit_types.items()],
        )
    )

    # downloads
    if result.downloads:
        parts.append("\n### 3.6 Downloads\n\n")
        parts.append(
            _table(
                ["File", "Source URL", "Saved to", "Size", "Started"],
                [
                    [
                        item.file_name,
                        item.source_url,
                        item.target_path,
                        item.file_size or "",
                        item.started_str,
                    ]
                    for item in result.downloads
                ],
            )
        )

    # cookies
    if result.cookie_hosts:
        parts.append("\n### 3.7 Cookie hosts (corroboration of page loads)\n\n")
        hosts = result.cookie_hosts[:max_rows]
        parts.append(
            _table(
                ["Host", "Cookies", "Last accessed", "Third party"],
                [
                    [
                        host["host"],
                        host["cookies"],
                        host["last_accessed"].strftime("%Y-%m-%d %H:%M:%S")
                        if host.get("last_accessed")
                        else "",
                        "yes" if host["third_party"] else "no",
                    ]
                    for host in hosts
                ],
            )
        )
        parts.append(_truncated_note(len(result.cookie_hosts), len(hosts)))

    # form history
    if result.form_history:
        parts.append("\n### 3.8 Typed form and search-bar entries\n\n")
        parts.append(
            "`formhistory.sqlite` records text physically entered at the keyboard, "
            "which is the strongest browser-side indicator of authorship.\n\n"
        )
        forms = result.form_history[:max_rows]
        parts.append(
            _table(
                ["Field", "Value", "Times used", "Last used"],
                [
                    [item.fieldname, item.value, item.times_used, item.last_used_str]
                    for item in forms
                ],
            )
        )
        parts.append(_truncated_note(len(result.form_history), len(forms)))

    # ------------------------------------------------------------ indicators
    assessment: Dict[str, Any] = result.assessment or {}
    parts.append("\n## 4. Indicator triage\n\n")
    parts.append(
        "Automated keyword triage. A score measures **topic**, never intent — "
        "see the interpretation caveats in section 5.\n\n"
    )
    parts.append(
        _table(
            ["Measure", "Value"],
            [
                ["Total weighted score", assessment.get("total_score", 0)],
                ["Rule hits", assessment.get("hit_count", 0)],
                ["Artefacts flagged", assessment.get("flagged_count", 0)],
                ["Highest severity observed", assessment.get("highest_severity", "info")],
            ],
        )
    )

    rules = assessment.get("rules_triggered", {})
    if rules:
        parts.append("\n**Categories triggered**\n\n")
        parts.append(
            _table(
                ["Category", "Severity", "Hits", "Example artefact"],
                [
                    [name, data["severity"], data["count"], (data["examples"] or [""])[0]]
                    for name, data in rules.items()
                ],
            )
        )

    flagged = assessment.get("flagged_items", [])[:max_rows]
    if flagged:
        parts.append("\n**Highest-scoring artefacts**\n\n")
        parts.append(
            _table(
                ["Score", "Severity", "Source", "Artefact", "Categories"],
                [
                    [
                        item["score"],
                        item["severity"],
                        item["source"],
                        item["text"][:110],
                        ", ".join(item["rules"]),
                    ]
                    for item in flagged
                ],
            )
        )

    corroboration = assessment.get("corroboration", {})
    if corroboration:
        parts.append("\n### 4.1 Cross-artefact corroboration\n\n")
        parts.append(
            f"{corroboration.get('confirmed_typed_count', 0)} search term(s) appear in "
            "**both** `formhistory.sqlite` and `places.sqlite`, indicating deliberate "
            "keyboard entry rather than redirection or auto-suggestion.\n\n"
        )
        both = corroboration.get("typed_and_in_history", [])[:max_rows]
        if both:
            parts.append(_table(["Term confirmed as typed"], [[term] for term in both]))
        history_only = corroboration.get("history_only", [])[:max_rows]
        if history_only:
            parts.append("\n_Present in history only (weaker authorship evidence):_\n\n")
            parts.append(_table(["Term"], [[term] for term in history_only]))

    # ------------------------------------------------------------ conclusion
    interp = assessment.get("interpretation", {})
    parts.append("\n## 5. Conclusion and limitations\n\n")
    parts.append(f"**Verdict:** {interp.get('verdict', 'INCONCLUSIVE')}\n\n")

    if interp.get("supporting_observations"):
        parts.append("**Observations that narrow the activity**\n\n")
        for line in interp["supporting_observations"]:
            parts.append(f"- {line}\n")
        parts.append("\n")

    if interp.get("innocent_explanations"):
        parts.append("**Explanations consistent with the same evidence**\n\n")
        for line in interp["innocent_explanations"]:
            parts.append(f"- {line}\n")
        parts.append("\n")

    if interp.get("recommended_corroboration"):
        parts.append("**Recommended corroborating enquiries**\n\n")
        for line in interp["recommended_corroboration"]:
            parts.append(f"- {line}\n")
        parts.append("\n")

    parts.append(f"> {interp.get('caveat', '')}\n")
    parts.append(
        "\nAny disciplinary or legal action should follow organisational policy "
        "and further contextual investigation, not this report alone "
        "(ACPO Principle 4 — the examiner remains responsible for the "
        "interpretation as well as the integrity of the evidence).\n"
    )

    if result.errors:
        parts.append("\n### Processing notes\n\n")
        for error in result.errors:
            parts.append(f"- {error}\n")

    # ----------------------------------------------------------- audit trail
    if trail is not None and len(trail):
        parts.append("\n## 6. Audit trail\n\n")
        parts.append(trail.to_markdown())

    parts.append("\n---\n")
    parts.append(
        "Association of Chief Police Officers (2012) *ACPO Good Practice Guide "
        "for Digital Evidence*, 5th edn.\n"
    )
    return "".join(parts)


def write_markdown(
    result: CaseResult,
    path: os.PathLike | str,
    trail: Optional[AuditTrail] = None,
    max_rows: int = MAX_TABLE_ROWS,
) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_markdown(result, trail, max_rows), encoding="utf-8")
    return path
